BEGIN;
DROP TABLE IF EXISTS users ,events ;
--
CREATE TABLE IF NOT EXISTS users (
id        SERIAL  PRIMARY KEY ,
name      VARCHAR(50) NOT NULL,
user_name VARCHAR(50) NOT NULL unique ,
password  VARCHAR(50) NOT NULL
);
--
CREATE TABLE IF NOT EXISTS events (
id SERIAL  PRIMARY KEY ,
user_id  INTEGER REFERENCES users(id),
title TEXT NOT NULL ,
content TEXT NOT NULL ,
date DATE NOT NULL ,
time TIME NOT NULL
);

COMMIT;